### ISSUE TITLE
Charla: Rust como alternativa a C/C++

### ISSUE THREAD

**Issue by MortimerGoro** [MadRust/talks#1]
# Title / Título
Rust como alternativa a C/C++

# Description / Descripción

Rust está posicionado como una de las alternativas reales a C/C++. En esta charla voy a contar varias experiencias y desafios de desarrollo en C++ en proyectos reales y analizar como hubiera podido ayudar Rust en esas situaciones. Quiero dar una visión sincera de como ve el lenguaje Rust alguien que es y ha sido fan de C++ durante muchos años, las cosas que más le han gustado y las que menos del lenguaje.

# Speaker Bio / Bio del Ponente

Imanol Fernández (@MortimerGoro) es ingeniero de plataforma en Mozilla. Trabaja en el core de WebVR/WebGL de Servo y Firefox implementando las APIs y optimizaciones necesarias para que WebGL y WebVR tengan el mejor rendimiento posible, tanto en plataformas móviles como en desktop. Anteriormente fue Lead Developer en Ludei y uno de los cerebros detrás del core y motor de render HTML5 acelerado de Cocoon. Le encanta la programación, y cuando se propone un reto no descansa hasta lograrlo. Constantemente anda moviéndose entre C++, Rust, JavaScript, Objective-C y Java, implementando tanto APIs a alto nivel como buscando tweaks a bajo nivel para ahorrarse cientos de microsegundos en código de alto rendimiento. Gamer desde que tiene recuerdos, es un ultra-fan de Dragon Ball y Metal Gear. También ha desarrollado juegos nativos para iOS/Android habiendo conseguido más de 5 millones de descargas en total.

# Level / Nivel

Iniciación/Intermedio

# Duration / Duración

30-40 minutos

**Comment by ferjm** [comment]
Esta charla tuvo lugar en el meetup del 5 de Abril. En breve subiremos el video y las slides. Muchas gracias!
