### ISSUE TITLE
Usar Rust para programar una consola RG-300 (u otras basadas en MIPS y RetroFW)

### ISSUE THREAD

**Issue by alexpdp7** [MadRust/talks#17]
Buenas,

Estas navidades me pedí una consola RG-300:

https://retrogame300.com/products/retro-game-300

Es un cacharrito muy mono tipo GameBoy que corre un Linux extraño y soporta un chorro de emuladores; nada muy potente porque lleva una CPU MIPS que no da para mucho y no tiene ningún tipo de GPU.

Mi idea era forzarme a aprender más Rust escribiendo un jueguecillo en el cacharro, ya que no da para mucho más que C/C++/Go/Rust, con 128mb de RAM va muy justo para cualquier lenguaje interpretado.

Me he topado con mil obstáculos (no es una plataforma muy soportada por Rust, el hardware de gráfico y sonidos tiene poco soporte de motores de juegos, etc.), pero al final he podido compilar un programilla que hace gráficos, sonido y lee los controles. Lo he publicado todo en:

https://github.com/alexpdp7/retrofw2-rust

Le he podido pegar un buen empujón porque he estado entre trabajos y tal, pero ahora vuelvo al tajo y no creo que tenga mucho tiempo para escribir ningún jueguecillo, pero bueno...

Podría darse una charla sobre el tema. En el pasado di una bastante cutre en BcnRust ( https://www.youtube.com/watch?v=fLHKRmtQxio ), por el tema de que había muy pocos ponentes y tal. La verdad que la charla sería bastante cutre (mi conclusión sería que estos cacharros son muy monos y baratos, pero que probablemente si quieres hacer Rust haya opciones mejores), pero si necesitáis una charla para completar un Meetup o necesitáis ponentes para animar el cotarro (al menos puedo servir de mal ejemplo :), no me importaría preparar una charla sobre el tema (especialmente si a los de BcnRust también les mola y la puedo dar dos veces).

Igual podría hacer una lightning talk, pero no lo veo muy claro...

**Comment by aruiz** [comment]
Pues la que diste antes no me parece tan cutre. A mi me parece un tema interesante, sobretodo si te centras en como usar Rust en entornos poco soportados (ya me toco a mi tocar un poco el tema en mi charla de UEFI usando no_std).

Me parece un tema muy llamantivo que puede atraer gente al evento, te animas a dalra en unas 3 semanas? Podemos ir concretando fecha mas adelante.

**Comment by alexpdp7** [comment]
Anoto que hay interés, así que voy a ir preparando la charla, pero entiendo que todo esto está suspendido. De momento hasta que no se levante la recomendación ministerial de no hacer desplazamientos no imprescindibles y de trabajar desde casa, no me plantearé hacer nada presencial.

En realidad, si hubiere interés tampoco me importaría hacerla telemáticamente, pero entiendo que es más bonito que se haga presencialmente.

**Comment by ereslibre** [comment]
Gracias igualmente @alexpdp7, si te apetece hablar sobre cualquier cosa relacionada ya sabes que tu contribución es bienvenida. Perdón por no haber tenido la suficiente agilidad para haber disfrutado tu charla en MadRust :(

**Comment by alexpdp7** [comment]
No hombre! Tampoco hubiese sido una charla tan buena :D

Simplemente justo pilló la pandemia y perdí yo inercia, no hay ningún problema por parte de MadRust :)

Ahora estoy haciendo cosillas con Rust, pero nada digno de charla, la verdad. Ya os comento si vuelvo a pillar el aparatito o hago algo digno de mención :)
