### ISSUE TITLE
El lado egoísta de Rust (mutabilidad, ownership y borrowing)

### ISSUE THREAD

**Issue by jleahred** [MadRust/talks#2]
# Título

El lado egogísta de Rust

# Descripción

¿Es necesario Rust? ¿Cuál es la situación actual? ¿Qué propone para mejorar?
 
Revisaremos 3 de las caraterísticas básicas de Rust que marcan una profunda diferencia de este lenguaje con los lenguajes populares y establecidos; y cómo nos puede ayudar a hacer un mejor software.

Mutability, ownership and borrowing

# Bio del Ponente

Trabajo principalmente con C++ en el entorno financiero desde hace muchos años.
Sistemas de tiempo real, distribuidos y orientado a microservicios, librerías reactivas y "seguras", cálculos...

Hacer software fiable ha sido siempre una prioridad para mí.

Adoro la programación funcional y soy colaborador en el meetup Haskell-Madrid

Me apasiona Haskell, Elixir/Erlang, la programación concurrente

Rust está entre mis lenguajes favoritos por la posibilidad de trabajar con muy poca mutabilidad, el borrowing y ownership, concurrencia segura, los traits, soporte de ADT, tooling, gestión de contenedores con estilo funcional, no null pointer, las excepciones no se llaman excepciones y "no se pueden" atrapar, rendimiento, facilidad para crear binarios sin dependencias...

# Level / Nivel

Intermedio

# Duration / Duración

40 minutos

**Comment by ferjm** [comment]
Esta charla tuvo lugar en el meetup del 5 de Abril. En breve subiremos el video y las slides. Muchas gracias!
