### ISSUE TITLE
This Week in Rust

### ISSUE THREAD

**Issue by jrvidal** [MadRust/talks#3]
No veo los eventos de MadRust en [This Week in Rust](https://this-week-in-rust.org). Para aparecer en **Upcoming Events**:

> If you are running a Rust event please add it to the [calendar](https://www.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com) to get it mentioned here. Email the [Rust Community Team](mailto:community-team@rust-lang.org) for access.

**Comment by ferjm** [comment]
Acabo de añadir el evento al calendario. Muchas gracias por el recordatorio!
