### ISSUE TITLE
Sugerencia nueva estructura

### ISSUE THREAD

**Issue by ereslibre** [MadRust/talks#6]
Podríamos cambiar la estructura para hacer submit de nuevas charlas, propongo hacer algo así:

```
- 2018
  - 05
    - Charla 1
    - Charla 2
  - 06
    - Charla 1
    - Charla 2
```

Cada nueva charla en vez de ser un Issue sería un Pull request, y los contenidos de la charla podrían subirse con ella, de tal forma que si tenemos un clone del proyecto es trivial ver los nuevos contenidos y también charlas antiguas (podrían incluir posteriormente el link a youtube también, por ejemplo).

En cualquier caso, enhorabuena por los dos meetups que llevamos, gran comunidad y grandes organizadores. ¡Gracias!

**Comment by ferjm** [comment]
Gracias por la sugerencia!

Actualmente tenemos el [README](https://github.com/MadRust/talks#charlas-pasadas) para mantener un histórico de charlas pasadas y el detalle de las próximas charlas. Pero ciertamente depende de que alguien se acuerde de actualizarlo :).

Por confirmar: ¿lo que sugieres es que para proponer nuevas charlas los ponentes deberían crear un Pull Request modificando el contenido del README con su propuesta de charla? Me parece buena idea. Podríamos mantener la [plantilla](https://github.com/MadRust/talks/blob/master/PROPOSAL_TEMPLATE.md) actual con los detalles de la charla como descripción del PR para no perder esa información.

**Comment by ereslibre** [comment]
Hola @ferjm!

> Por confirmar: ¿lo que sugieres es que para proponer nuevas charlas los ponentes deberían crear un Pull Request modificando el contenido del README con su propuesta de charla? Me parece buena idea. Podríamos mantener la plantilla actual con los detalles de la charla como descripción del PR para no perder esa información.

Sí, exactamente. Aunque creo que además podemos aprovechar para añadir contenido si aplica (si alguien tiene slides hechas en PDF podría subirlas a un directorio `2018/05/Charla A`, o si hubo otros recursos, por ejemplo (snippets... cualquier cosa). Aunque quizá el repo puede acabar siendo un poco cajón desastre, pero si todo está organizado supongo que sería bastante útil para nunca perder contenidos (sé que binarios con git = atrocidad, pero en este caso en concreto podría funcionar :).

**Comment by ereslibre** [comment]
Cerrando por ahora, siempre se puede retomar después.
